server:
  port: 8082

spring:
  application:
    name: organization-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/lms_platform}
    username: ${SPRING_DATASOURCE_USERNAME:lms}
    password: ${SPRING_DATASOURCE_PASSWORD:lms_password}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    username: ${SPRING_RABBITMQ_USERNAME:lms}
    password: ${SPRING_RABBITMQ_PASSWORD:lms_password}

management:
  endpoints:
    web:
      exposure:
        include: health,info
